FROM php:8.2-cli

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git curl unzip libpq-dev zip \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# STEP 1: composer files first
COPY composer.json composer.lock ./

# STEP 2: install dependencies
RUN composer install --no-dev --optimize-autoloader

# STEP 3: copy app AFTER
COPY . .

EXPOSE 10000

CMD ["php", "-S", "0.0.0.0:10000", "-t", "public"]